### ISSUE TITLE
[feature request] could you please add ahci drive support as an option?

### ISSUE THREAD

**Issue by slitilanber** [jirutka/qemu-openrc#11]
since scsi driver has not been included in some customised disk images, i have to change qemu.initd file.

**Comment by jirutka** [comment]
I’m not using this script anymore, so I don’t have much interest in improving it, but pull requests are always welcome.

**Comment by mcassaniti** [comment]
@slitilanber It seems that you've got quite a set of useful updates from the initial version by @jirutka. Can I suggest you look at getting these merged? If that doesn't work for @jirutka then your repository could potentially supersede this one.

I've also found a few extra features from the other forks of this repository. I don't know if you @slitilanber wish to look into also submitting PRs for them. I noted USB tablet support and serial socket support.

**Comment by slitilanber** [comment]
> @slitilanber It seems that you've got quite a set of useful updates from the initial version by @jirutka. Can I suggest you look at getting these merged? If that doesn't work for @jirutka then your repository could potentially supersede this one.
> 
> I've also found a few extra features from the other forks of this repository. I don't know if you @slitilanber wish to look into also submitting PRs for them. I noted USB tablet support and serial socket support.

@mcassaniti Thanks for your sugguest. I    also hope my scripts could be accepted and be merged. However I am not a coder and don't have enough knowledge to ensure there are not bugs in these scripts.
